# Site settings
title: Barely Usable
email: contact@barelyusable.com
description: > # this means to ignore newlines until "baseurl:"
  Everyday things and their usability.
baseurl: ""
url: "http://www.barelyusable.com" # the base hostname & protocol for your site
twitter_username: barelyusable
#github_username:

permalink: /:title

# Build settings
markdown: kramdown
