# Site settings
title: BARELY USABLE
email: contact@barelyusable.com
description: > # this means to ignore newlines until "baseurl:"
  Everyday things and their usability.
baseurl: ""
url: "http://barelyusable.com" # the base hostname & protocol for your site
twitter_username: barelyusable
#github_username:

# Build settings
markdown: kramdown
